spring:
  data:
    mongodb:
      uri: ${MONGO_DB_URL}
server:
  port: 8010

logging:
  file:
    name: logs/daedalus.log
    path: daedalus
  level:
    com.geppetto: info
  pattern:
    dateformat: "dd-MM-yyyy hh:mm:ss aa"



























